global:
  message: welcome to microservices environment !!
logging:
  level:
    root: INFO
management:
    endpoints:
      web:
        exposure:
          include: health, info, refresh
endpoints:
   health:
     show-details: always
